default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "secret") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  timeout: 5000

local:
  <<: *default
  database: rails_template_local

test:
  <<: *default
  database: rails_template_test

development:
  <<: *default
  database: rails_template_dev

production:
  <<: *default
  database: rails_template_prd
